require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BugStatusesController do

  # This should return the minimal set of attributes required to create a valid
  # BugStatus. As you add validations to BugStatus, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all bug_statuses as @bug_statuses" do
      bug_status = BugStatus.create! valid_attributes
      get :index
      assigns(:bug_statuses).should eq([bug_status])
    end
  end

  describe "GET show" do
    it "assigns the requested bug_status as @bug_status" do
      bug_status = BugStatus.create! valid_attributes
      get :show, :id => bug_status.id
      assigns(:bug_status).should eq(bug_status)
    end
  end

  describe "GET new" do
    it "assigns a new bug_status as @bug_status" do
      get :new
      assigns(:bug_status).should be_a_new(BugStatus)
    end
  end

  describe "GET edit" do
    it "assigns the requested bug_status as @bug_status" do
      bug_status = BugStatus.create! valid_attributes
      get :edit, :id => bug_status.id
      assigns(:bug_status).should eq(bug_status)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BugStatus" do
        expect {
          post :create, :bug_status => valid_attributes
        }.to change(BugStatus, :count).by(1)
      end

      it "assigns a newly created bug_status as @bug_status" do
        post :create, :bug_status => valid_attributes
        assigns(:bug_status).should be_a(BugStatus)
        assigns(:bug_status).should be_persisted
      end

      it "redirects to the created bug_status" do
        post :create, :bug_status => valid_attributes
        response.should redirect_to(BugStatus.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bug_status as @bug_status" do
        # Trigger the behavior that occurs when invalid params are submitted
        BugStatus.any_instance.stub(:save).and_return(false)
        post :create, :bug_status => {}
        assigns(:bug_status).should be_a_new(BugStatus)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BugStatus.any_instance.stub(:save).and_return(false)
        post :create, :bug_status => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bug_status" do
        bug_status = BugStatus.create! valid_attributes
        # Assuming there are no other bug_statuses in the database, this
        # specifies that the BugStatus created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BugStatus.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => bug_status.id, :bug_status => {'these' => 'params'}
      end

      it "assigns the requested bug_status as @bug_status" do
        bug_status = BugStatus.create! valid_attributes
        put :update, :id => bug_status.id, :bug_status => valid_attributes
        assigns(:bug_status).should eq(bug_status)
      end

      it "redirects to the bug_status" do
        bug_status = BugStatus.create! valid_attributes
        put :update, :id => bug_status.id, :bug_status => valid_attributes
        response.should redirect_to(bug_status)
      end
    end

    describe "with invalid params" do
      it "assigns the bug_status as @bug_status" do
        bug_status = BugStatus.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BugStatus.any_instance.stub(:save).and_return(false)
        put :update, :id => bug_status.id, :bug_status => {}
        assigns(:bug_status).should eq(bug_status)
      end

      it "re-renders the 'edit' template" do
        bug_status = BugStatus.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BugStatus.any_instance.stub(:save).and_return(false)
        put :update, :id => bug_status.id, :bug_status => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bug_status" do
      bug_status = BugStatus.create! valid_attributes
      expect {
        delete :destroy, :id => bug_status.id
      }.to change(BugStatus, :count).by(-1)
    end

    it "redirects to the bug_statuses list" do
      bug_status = BugStatus.create! valid_attributes
      delete :destroy, :id => bug_status.id
      response.should redirect_to(bug_statuses_url)
    end
  end

end
