require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WorkCategoriesController do

  # This should return the minimal set of attributes required to create a valid
  # WorkCategory. As you add validations to WorkCategory, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all work_categories as @work_categories" do
      work_category = WorkCategory.create! valid_attributes
      get :index
      assigns(:work_categories).should eq([work_category])
    end
  end

  describe "GET show" do
    it "assigns the requested work_category as @work_category" do
      work_category = WorkCategory.create! valid_attributes
      get :show, :id => work_category.id
      assigns(:work_category).should eq(work_category)
    end
  end

  describe "GET new" do
    it "assigns a new work_category as @work_category" do
      get :new
      assigns(:work_category).should be_a_new(WorkCategory)
    end
  end

  describe "GET edit" do
    it "assigns the requested work_category as @work_category" do
      work_category = WorkCategory.create! valid_attributes
      get :edit, :id => work_category.id
      assigns(:work_category).should eq(work_category)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WorkCategory" do
        expect {
          post :create, :work_category => valid_attributes
        }.to change(WorkCategory, :count).by(1)
      end

      it "assigns a newly created work_category as @work_category" do
        post :create, :work_category => valid_attributes
        assigns(:work_category).should be_a(WorkCategory)
        assigns(:work_category).should be_persisted
      end

      it "redirects to the created work_category" do
        post :create, :work_category => valid_attributes
        response.should redirect_to(WorkCategory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved work_category as @work_category" do
        # Trigger the behavior that occurs when invalid params are submitted
        WorkCategory.any_instance.stub(:save).and_return(false)
        post :create, :work_category => {}
        assigns(:work_category).should be_a_new(WorkCategory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WorkCategory.any_instance.stub(:save).and_return(false)
        post :create, :work_category => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested work_category" do
        work_category = WorkCategory.create! valid_attributes
        # Assuming there are no other work_categories in the database, this
        # specifies that the WorkCategory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WorkCategory.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => work_category.id, :work_category => {'these' => 'params'}
      end

      it "assigns the requested work_category as @work_category" do
        work_category = WorkCategory.create! valid_attributes
        put :update, :id => work_category.id, :work_category => valid_attributes
        assigns(:work_category).should eq(work_category)
      end

      it "redirects to the work_category" do
        work_category = WorkCategory.create! valid_attributes
        put :update, :id => work_category.id, :work_category => valid_attributes
        response.should redirect_to(work_category)
      end
    end

    describe "with invalid params" do
      it "assigns the work_category as @work_category" do
        work_category = WorkCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WorkCategory.any_instance.stub(:save).and_return(false)
        put :update, :id => work_category.id, :work_category => {}
        assigns(:work_category).should eq(work_category)
      end

      it "re-renders the 'edit' template" do
        work_category = WorkCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WorkCategory.any_instance.stub(:save).and_return(false)
        put :update, :id => work_category.id, :work_category => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested work_category" do
      work_category = WorkCategory.create! valid_attributes
      expect {
        delete :destroy, :id => work_category.id
      }.to change(WorkCategory, :count).by(-1)
    end

    it "redirects to the work_categories list" do
      work_category = WorkCategory.create! valid_attributes
      delete :destroy, :id => work_category.id
      response.should redirect_to(work_categories_url)
    end
  end

end
